run_tag: "lst_4_mst_1"
targets:
  mc_simtel: false
  mc_dl1: false
  mc_dl1_merged: false
  mc_dl2: false
  rf_energy_regressor: false
  rf_particle_classifier: false
  rf_geometry_reconstructor: false
  rf_performance_plots: false
  irfs: true
  irfs_plots: true

plugins: ["fermi"] #, "stereo_combiner"]
user_config_dir: ./examples/thesis/subarrays/lst_4_mst_1/
user_env_dir: null

# [zen, az]
pointings:
  - [20, 0]

obstimes: # hours
  - 50
  - 5
  - 0.5

inputs:
  mc_simtel: null
  mc_dl1: null
  mc_dl1_merged: /home/jonas/repos/sandsnake_dpps/build/full_array/mc/dl1_merged
  mc_dl2: null # Only if all three properties are reconstructed!
  models: /home/jonas/repos/sandsnake_dpps/build/full_array/models
  irfs: null
  benchmarks: null
  cuts: null

# RF training split
train_size: 0.6
cuts_size: 0.5
