run_tag: "5_fov_bins"
user_config_dir: ./examples/lukas_thesis/configs
user_env_dir: null

targets:
  mc_simtel: false
  mc_dl1: false
  mc_dl1_merged: false
  mc_dl2: false
  rf_energy_regressor: false
  rf_particle_classifier: false
  rf_geometry_reconstructor: false
  rf_performance_plots: false
  irfs: true
  irfs_plots: true

inputs:
  mc_simtel: null
  mc_dl1: null #/cephfs/projects/CTA/simulations/v0.23.1/PROD6/LaPalma/dl1/
  mc_dl1_merged: null
  mc_dl2: /cephfs/users/lbeiske/build_sandsnake_dpps/full_array/mc/dl2/ # Only if all three properties are reconstructed!
  models: null
  irfs: null
  benchmarks: null
  cuts: null

# Gamma MC sample for both cut optimization and IRF computation.
# "gamma" selects point-like MC; "gamma_diffuse" selects diffuse MC.
irfs:
  gamma_particle: gamma_diffuse

# [zen, az]
pointings:
  - [20, 180]

obstimes:
  # hours
  - 50
  - 5
  - 0.5

# RF training split
train_size: 0.25
cuts_size: 0.25

plugins: null #["fermi"]
