# ======================================================================
# ctapipe-optimize-event-selection config file
# version: VERSION
#
# Configuration for calculating G/H and spatial selection ("theta") cuts
# ======================================================================

EventSelectionOptimizer:
  gamma_target_spectrum: CRAB_HEGRA
  proton_target_spectrum: IRFDOC_PROTON_SPECTRUM
  electron_target_spectrum: IRFDOC_ELECTRON_SPECTRUM
  obs_time: 50 hour
  optimization_algorithm: "PointSourceSensitivityOptimizer"

DL2EventPreprocessor:
  energy_reconstructor: "RandomForestRegressor"
  geometry_reconstructor: "disp"
  gammaness_classifier: "RandomForestClassifier"

  DL2EventQualityQuery:
    quality_criteria:
      - ["multiplicity > 1", "np.count_nonzero(disp_telescopes,axis=1) >= 2"]
      - ["valid classifier", "RandomForestClassifier_is_valid"]
      - ["valid geom reco", "disp_is_valid"]
      - ["valid energy reco", "RandomForestRegressor_is_valid"]

DefaultRecoEnergyBins:
  reco_energy_min: 0.015 TeV
  reco_energy_max: 150 TeV
  reco_energy_n_bins_per_decade: 5

ThetaPercentileCutCalculator:
  theta_min_angle: -1 deg
  theta_max_angle: 0.35 deg
  theta_fill_value: 0.35 deg
  smoothing:
  target_percentile: 68
  min_counts: 10

GhPercentileCutCalculator:
  target_percentile: 68
  min_counts: 10
  smoothing:

PointSourceSensitivityOptimizer:
  min_background_fov_offset: 0.35 deg
  max_background_fov_offset: 1.05 deg
  initial_gh_cut_efficency: 0.4
  max_gh_cut_efficiency: 0.8
  gh_cut_efficiency_step: 0.05
  alpha: 0.2
