run_tag: "full_array"
user_config_dir: "/home/jonas"
user_env_dir: "/home/jonas"

targets:
  mc_simtel: false
  mc_dl1: true
  mc_dl1_merged: false
  mc_dl2: false
  rf_energy_regressor: false
  rf_particle_classifier: false
  rf_geometry_reconstructor: false
  rf_performance_plots: true
  irfs: true
  irfs_plots: true

inputs:
  mc_simtel: null
  mc_dl1: /home/jonas/repos/sandsnake_dpps/data/CTAO/mc/dl1/
  mc_dl1_merged: null
  mc_dl2: null # Only if all three properties are reconstructed!
  models: null
  irfs: null
  benchmarks: null
  cuts: null

# [zen, az]
pointings:
  - [20, 0]

obstimes: # hours
  - 50
  - 5

# RF training split
train_size: 0.6
cuts_size: 0.5

plugins: null #["fermi"]
